# Generated by Django 4.0.4 on 2022-05-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAcademico', '0003_carrera_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='vigencia',
        ),
    ]
