# Generated by Django 4.0.4 on 2022-05-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAcademico', '0004_remove_estudiante_vigencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='dni',
        ),
    ]
