# Generated by Django 4.0.4 on 2022-05-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAcademico', '0005_remove_estudiante_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='sexo',
        ),
    ]
